on:
  push:
    branches: [dev]
jobs:
  build-push-deploy-docker-image:
    runs-on: ubuntu-latest
    name: Build and Deploy ${{ github.ref_name }} ${{ github.event.repository.name }}
    steps:
      - uses: devopsprabin/github-action-dev@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_actor: ${{ github.actor }}
          ssh_enable: "true"
          ssh_host: ${{ secrets.SSH_HOST_DEV }}
          ssh_user: ${{ secrets.SSH_USER_DEV }}
          ssh_port: ${{ secrets.SSH_PORT_DEV }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          deploy_folder_path: ${{ vars.DEPLOY_FOLDER_PATH_DEV }}
          deploy_command: ${{ vars.DEPLOY_COMMAND_DEV }}
          discord_enable: "true"
          discord_webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID_DEV }}
          discord_webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN_DEV }}
